### ISSUE TITLE
Toggle

### ISSUE THREAD

**Issue by mbwilding** [jiriks74/presence.nvim#38]
### Is your feature request related to a problem?

https://github.com/pwnxpl0it/presence.nvim/commit/a5dfc0f4786d72fc2d6c8c77e0e9437937470fb5

Here is a commit that can be referenced. Allows for toggling it on and off. Useful when you are working on sensitive stuff.

### Describe the solution you'd like

https://github.com/pwnxpl0it/presence.nvim/commit/a5dfc0f4786d72fc2d6c8c77e0e9437937470fb5

**Comment by mbwilding** [comment]
Blacklisting was a better choice and that is already a feature.

**Comment by Insprill** [comment]
I know this is a touch old, but having a command to toggle the status quickly is a handy feature. Having to go into the config and blacklist a name/path is inconvenient if there's only one or two files that I don't want to be shown temporarily or if they're files that will soon be deleted.

**Comment by jiriks74** [comment]
@Insprill You can make a feature request if you want.
