### ISSUE TITLE
[Bug]: Pipe write error - EPIPE

### ISSUE THREAD

**Issue by SirFrey** [jiriks74/presence.nvim#53]
### Are you on the latest version?

- [X] I have updated to the latest version.

### Have you tried it with default config?

- [X] I have tried the default config.

### Description

Not able to display the information in Discord, I'm not sure if it is my VM not well configured to expose the socket to my OS (windows 11) or it's something related to the plugin, if you can help to debug this would be really helpful, like, I would like to know if at least Discord is tracking the info but for some reason is not displayed

### Neovim version

```markdown
NVIM: v0.10.0-dev-2913+g5371ed36b
Build type: RelWithDebInfo
LuaJIT: 2.1.1710088188
```

### OS information

5.15.146.1-microsoft-standard-WSL2 (Ubuntu)

### Steps to reproduce

1. just setup your config with the plugin (I only test it with lazyvim, I don't think that's something related with this):
```lua
return {
  "jiriks74/presence.nvim",
  event = "UIEnter",
  config = function()
    -- The setup config table shows all available config options with their default values:
    require("presence").setup({
      -- General options
      auto_update       = true,                       -- Update activity based on autocmd events (if `false`, map or manually execute `:lua package.loaded.presence:update()`)
      neovim_image_text = "The One True Text Editor", -- Text displayed when hovered over the Neovim image
      main_image        = "neovim",                   -- Main image display (either "neovim" or "file")
      log_level         = "debug",                    -- Log messages at or above this level (one of the following: "debug", "info", "warn", "error")
    })
  end,
}
```
2. init nvim with a file (or whatever, it doesn't matter really):
```bash
# like this
$ nvim .
# or this...
$ nvim
# or maybe this...
$ nvim <file>
```

### Logs

<details>

```
[presence.nvim] Setting up plugin for linux in WSL ("Ubuntu")
[presence.nvim] Duplicate options: `g:presence_auto_update` and setup option `auto_update`
[presence.nvim] Using Discord IPC socket path: /var/run/discord-ipc-0
[presence.nvim] Checking Discord IPC socket at /var/run/discord-ipc-0...
[presence.nvim] Using id 99f86f68-d68e-4974-a4cf-7295ee957447
[presence.nvim] Completed plugin setup
[presence.nvim] Getting nvim socket paths...
[presence.nvim] Executing command: `sh, -c, for file in /tmp/nvim*; do echo $file/0; done`
[presence.nvim] Checked Discord IPC socket, looks good!
[presence.nvim] Checked Discord IPC socket, looks good!
Welcome to LazyVim!
[presence.nvim] Got nvim socket paths: { "/tmp/nvim.moises/0" }
[presence.nvim] Registering as a new peer to 1 instance(s)...
[presence.nvim] Connected to remote nvim instance at /tmp/nvim.moises/0
[presence.nvim] Got nvim socket paths: { "/tmp/nvim.moises/0" }
[presence.nvim] Registering as a new peer to 1 instance(s)...
[presence.nvim] Connected to remote nvim instance at /tmp/nvim.moises/0
"init.lua" 26L, 623B written
[presence.nvim] Handling TextChanged event...
[presence.nvim] Connecting to Discord...
[presence.nvim] Connected to Discord
[presence.nvim] Authorizing with Discord...
[presence.nvim] Failed to authorize with Discord: Pipe write error - EPIPE
[presence.nvim] Pipe was closed
```

</details>

### Aditional info

If you need additional info, just tell me 😄

**Comment by SirFrey** [comment]
https://github.com/jiriks74/presence.nvim/assets/95328621/528f6e3a-4459-43c9-9a10-705cbd3c6bcf

**Comment by jiriks74** [comment]
Please read the [README]() next time before making an issue:

![image](https://github.com/jiriks74/presence.nvim/assets/54378412/f2c22307-3250-4868-af64-c66e3477457b)

If you go to the Wiki page you'll see that WSL2 is not supported and you can find some links to issues reported to Microsoft:

![image](https://github.com/jiriks74/presence.nvim/assets/54378412/04f706eb-ce0c-4202-9379-3e50f5bbdc1f)

**Comment by SirFrey** [comment]
My bad, but I did an investigation before to manually share the pipes trough **WSL2** to the **Windows's Discord Client** (With no success I guess, I have to test it manually and see if I can share data trough, I'll let you know).
take a look a this issue in the andweeb/presence.nvim plugin:
https://github.com/andweeb/presence.nvim/issues/36#issuecomment-1690148602
https://github.com/andweeb/presence.nvim/issues/36#issuecomment-2060437761

**Comment by jiriks74** [comment]
I know that it kind of worked for some people but it's not working well enough to be *officially supported*:

> Well forget what i said its not stable if close the nvim session then it will not work again until you restart the service
i dont know what the problem is also the error write failed 32: Broken pipe comes frequently

If you'd be able to make it work I will gladly add it to the Wiki

**Comment by SirFrey** [comment]
I could get it working with this: https://gist.github.com/ongyx/6b05e076db3a3243e6721c90c1dc21e6
weird initial setup but it works ^^

**Comment by SirFrey** [comment]
https://github.com/andweeb/presence.nvim/issues/36#issuecomment-1690148602
