### ISSUE TITLE
[FEAT]: Adding Typst Icon

### ISSUE THREAD

**Issue by foodornt** [jiriks74/presence.nvim#57]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Adding a typst.com icon
![typst icon](https://avatars.githubusercontent.com/u/67595261?s=200&v=4)

### Additional context

From [typst.app/legal/brand](https://typst.app/legal/brand):

> You may use the Typst name in the name of your package or project that in some way incorporates, depends on, extends, or references Typst. The name of the project must not imply that it is the Typst web app / IDE or compiler. The name must allow any reader to immediately grasp that the project is neither the Typst web app nor compiler.

**Comment by jiriks74** [comment]
Hello,
I'd only like to ask whether that icon has some license that would prevent me from using it. If not I'll gladly add it to the project.

**Comment by foodornt** [comment]
Yes it's okay to use
https://typst.app/legal/brand

**Comment by jiriks74** [comment]
Ok then, I'll add it. 
https://openproject.stefka.eu/projects/presence-dot-nvim/work_packages/73/activity

**Comment by jiriks74** [comment]
@foodornt Sorry for the delay, I have a lot on my plate RN.

Would you check out jiriks74/presence.nvim#65?

**Comment by foodornt** [comment]
Wish you best luck, thanks for your time bud 🙌
