### ISSUE TITLE
[Bug]: Buttons

### ISSUE THREAD

**Issue by nick22985** [jiriks74/presence.nvim#62]
### Are you on the latest version?

- [X] I have updated to the latest version.

### Have you tried it with default config?

- [X] I have tried the default config.

### Description

Check to see what Discord did with their API to fix buttons. I am unsure if they removed this or if they have updated something. If this can no longer be used clean up code base to remove buttons

This is a issue with discord changing their sdk library recently.

### Neovim version

```markdown
n/a
```

### OS information

n/a

### Steps to reproduce

have buttons

### Logs

n/a

**Comment by jiriks74** [comment]
I'll take a look as soon as set up my NeoVim again. I've switched systems and hasn't gotten around updating my config yet. I'll try to speed it up to look into this.

**Comment by nick22985** [comment]
Buttons dont show on your own account anymore due to a discord change. If you log in on another browser they show up. Can be closed as it is working.

![image](https://github.com/user-attachments/assets/bb770819-a391-4e76-95ed-c3d7d2fd5dfc)
![image](https://github.com/user-attachments/assets/1999d569-51a7-4f12-89a9-0a389ae9a4a4)
