### ISSUE TITLE
[Bug]: Lazy.nvim is failing to update presence.nvim (checkout failed)

### ISSUE THREAD

**Issue by ficd0** [jiriks74/presence.nvim#67]
### Are you on the latest version?

- [X] I have updated to the latest version.

### Have you tried it with default config?

- [X] I have tried the default config.

### Description

Attempting to update to the latest version with `lazy.nvim` is failing.

### Neovim version

```markdown
NVIM v0.11.0-dev-1137+g72a1df6065
Build type: RelWithDebInfo
LuaJIT 2.1.1727870382
```

### OS information

Arch Linux x86_64

### Steps to reproduce

1. Attempt to install/update `presence` with the following Lazy spec:
```lua
{
  "jiriks74/presence.nvim",
}
```

### Logs

<details>

```
    ● presence.nvim 6.01ms  UIEnter
        dir    /home/fic/.local/share/nvim/lazy/presence.nvim
        url    https://github.com/jiriks74/presence.nvim
        branch main
        commit df0a0b5
        readme README.md
        event   UIEnter 

      ✔ [task] fetch 816.22ms
      ✔ [task] status 383.77ms
      ✔ [task] checkout 132.61ms
        fatal: not a git repository: .github/workflows/actions/cache-apt-pkgs-action/../../../../.git/modules/.github/workflows/actions/cache-apt-pkgs-action
```

</details>

**Comment by jiriks74** [comment]
Oh for God's sake. One thing gets fixed, another one gets broken.

This is caused by 8117a074d563361dca6bb0070f67e6046e6186e3

I'll look into this soon.

**Comment by ficd0** [comment]
Thanks! I've set `pin=true` for now. Since the commit seems to just be CI/CD related, at least my locally installed version of the plugin is working normally. However, I suspect new users will be unable to install the plugin.

In general, may I suggest creating tagged "releases"? This allows users to specify the following in `lazy.nvim`:

```lua
{
  "jiriks74/presence.nvim",
  version = "*", -- pulls the latest release instead of the latest commit
}
```

This way, users have a guaranteed way to pull a known-to-be-stable version of the plugin, in case something is broken in the main branch.

**Comment by jiriks74** [comment]
I was thinking of setting something like this up but there's a lot of things to take care of that I so far didn't have the time and energy to do. If you're willing to look at the code you'll probably agree that it needs to be split up so that it's more readable. The `init.lua` is `1325` lines long so it's hard to navigate (at least for me).

I'll try to finally look deeper into the code base this holiday.

**Comment by ficd0** [comment]
I don't think it needs to be written into the code base at all. As long as there is a stable branch (or commit, for that matter), you can easily create releases on the Github website. The releases don't need to contain anything other than the source code (which is handled by GitHub automatically), basically just the "tag" matters -- it lets `lazy.nvim` pull the version associated with the latest "release" instead of on the main branch. So, if things are broken (like right now), there is always a pinned version people can fall back to easily.

**Comment by jiriks74** [comment]
Sounds good enough. I'll be backing up my changes to the CI system and I'll revert the commit in the following minutes.
